blueprint:
  name: Interlock
  description: Turns off one entity when the other one is turned on
  domain: automation
  input:
    entity_1:
      name: First entity
      selector:
        entity: {}
    entity_2:
      name: Second entity
      selector:
        entity: {}
mode: single
max_exceeded: silent
variables:
  entity_1: !input 'entity_1'
  entity_2: !input 'entity_2'
trigger:
- platform: state
  entity_id: 
  - !input 'entity_1'
  - !input 'entity_2'
condition: '{{ trigger.to_state.state == "on" }}'
action:
- service: homeassistant.turn_off
  target:
    entity_id: >
      {% if trigger.from_state.entity_id == entity_1 %}
      {{ entity_2 }}
      {% else %}
      {{ entity_1 }}
      {% endif %}
