blueprint:
  name: Synchronize states
  description: Synchronize the on/off state of 2 entities
  domain: automation
  input:
    entity_1:
      name: First entity
      selector:
        entity:
          multiple: false
    entity_2:
      name: Second entity
      selector:
        entity:
          multiple: false
mode: single
max_exceeded: silent
variables:
  entity_1: !input 'entity_1'
  entity_2: !input 'entity_2'
trigger:
- platform: state
  entity_id: 
  - !input 'entity_1'
  - !input 'entity_2'
  to:
    - 'on'
    - 'off'
condition: '{{ states(entity_1) != states(entity_2) }}'
action:
- service: homeassistant.turn_{{ trigger.to_state.state }}
  target:
    entity_id: >
      {% if trigger.from_state.entity_id == entity_1 %}
      {{ entity_2 }}
      {% else %}
      {{ entity_1 }}
      {% endif %}
